name = "Circus"
uuid = "e1f17670-9e8c-4d1f-b9ce-7ab5ca400c46"
authors = ["Roger Behling", "Yunier Bello-Cruz", "Luiz-Rafael Santos", "Hugo Lara Urdaneta", "Davi Sales Barreira"]
version = "0.1.0"

[deps]
Clp = "e2554f3b-3117-50c0-817c-e040a3ddf72d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
